name: GitHub Actions Örneği

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Git Identity
      run: |
        git config --global user.email "beyaziesra@gmail.com"
        git config --global user.name "Esra Yılmaz"

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Dosya Oluştur ve Güncelle
      run: |
        echo "Merhaba, GitHub Actions!" > hello.txt
        git add hello.txt
        git commit -m "GitHub Actions ile dosya oluşturuldu veya güncellendi"
        git push --force "https://github.com/owner/repo.git" main
