name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.x # Jekyll sürümünüze uygun Ruby sürümünü seçin.

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll Site
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      run: |
        # git config --global user.email "beyaziesra@gmail.com"
        # git config --global user.name "Esra Yılmaz"
        cd _site
        git init
        git add .
        git commit -m "Deployed using GitHub Actions..."
        git push --force --quiet "https://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@github.com/${{ github.repository }}.git" master:gh-pages
